config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'

  resources :recipes, only: [:index, :show]
end

app/models/base.rb
class Base
  include ContentfulRenderable

  SPACE_ID = ENV['SPACE_ID']
  ACCESS_TOKEN = ENV['ACCESS_TOKEN']

  def self.space_id
    SPACE_ID
  end

  def self.access_token
    ACCESS_TOKEN
  end

  # Override in your model
  def self.content_type_id
  end

  attr_accessor :contentful_id

  def initialize(contentful_id)
    @contentful_id = contentful_id
  end
end

app/models/concerns/contentful_renderable.rb
module ContentfulRenderable
  extend ActiveSupport::Concern

  def self.included(base)
    base.extend(ClassMethods)
  end

  # Overridable
  # Override this method to change the parameters set for your Contentful query on each specific model
  # For more information on queries you can look into: https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters
  def render
    begin
      self.class.client.entries(content_type: self.class.content_type_id, include: 2, "sys.id" => contentful_id).first
    rescue Contentful::Error
      return nil
    end
  end

  module ClassMethods
    def client
      @client ||= Contentful::Client.new(
        access_token: Base.access_token,
        space: Base.space_id,
        dynamic_entries: :auto,
        raise_errors: true,
        raise_for_empty_fields: false
      )
    end

    # Overridable
    # Override this method to change the parameters set for your Contentful query on each specific model
    # For more information on queries you can look into: https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters
    def render_all
      begin
        client.entries(content_type: content_type_id, include: 2)
      rescue Contentful::Error
        return []
      end
    end
  end
end

app/models/recipe.rb
class Recipe < Base
  include ContentfulRenderable

  def self.content_type_id
    'recipe'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.render_all
  end

  def show
    @recipe = Recipe.new(params[:id]).render
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarleySpoonChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
  </head>

  <body>
    <h1 class="site-heading text-center text-white d-none d-lg-block">
      <span class="site-heading-upper mb-3">Marley Spoon</span>
      <span class="site-heading-lower">Recipes</span>
      <hr>
    </h1>

    <%= yield %>

    <!-- Footer -->
    <footer class="footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 h-100 text-center text-lg-left my-auto">
            <p class="small mb-4 mb-lg-0">&copy; Marley Spoon 2020. All Rights Reserved.</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/recipes/_error.html.erb
<section class="page-section">
  <div class="container">
    <div class="intro">
      <div class="error">
        <h2 class="section-heading">
          <p class="section-heading-lower"><%= message %></p>
        </h2>
      </div>
    </div>
  </div>
</section>

app/views/recipes/index.html.erb
<% if @recipes.empty? %>
  <%= render partial: "error", locals: { message: "There are no available recipes right now, please try later" } %>
<% else %>
  <% @recipes.each do |recipe| %>
    <section class="page-section clearfix">
      <div class="container">
        <div class="intro">
          <%= link_to recipe_path(id: recipe.id) do %>
            <%= image_tag recipe.photo.image_url, class: "intro-img img-fluid mb-3 mb-lg-0 rounded" %>
          <% end %>
          <div class="intro-text left-0 text-center bg-faded p-5 rounded">
            <h2 class="section-heading mb-4">
              <span class="section-heading-lower"><%= recipe.title %></span>
            </h2>
            <div class="intro-button mx-auto">
              <a class="btn btn-primary btn-xl" href="<%= recipe_path(id: recipe.id) %>">See recipe!</a>
            </div>
          </div>
        </div>
      </div>
    </section>
  <% end %>
<% end %>

app/views/recipes/show.html.erb
<% if @recipe %>
  <section class="page-section">
    <div class="container">
      <div class="product-item">
        <div class="product-item-title d-flex">
          <div class="bg-faded p-5 d-flex mr-auto rounded">
            <h2 class="section-heading mb-0">
              <span class="section-heading-upper">
                <% if @recipe.tags %>
                  <% @recipe.tags.each do |tag| %>
                    <span class="badge badge-warning"><%= tag.name %></span>
                  <% end %>
                <% end %>
                <h1><%= @recipe.title %></h1>
              </span>
              <span class="section-heading-lower"><h3><%= @recipe&.chef&.name %></h3></span>
            </h2>
          </div>
        </div>
        <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="<%= @recipe.photo.image_url %>" alt="">
        <div class="product-item-description d-flex ml-auto">
          <div class="bg-faded p-5 rounded">
            <p class="mb-0"><%= @recipe.description %></p>
            <div class="intro-button mx-auto">
              <a class="btn btn-primary btn-xl" href="<%= recipes_path %>">Go Back To Recipes</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
<% else %>
  <%= render partial: "error", locals: { message: "It is not possible to see the recipe, please try later" } %>
<% end %>